export { default as Header } from './header/Header'
export { default as Hero } from './hero/Hero'
export { default as ServiceCard } from './service-card/ServiceCard'
export { default as Services } from '@/components/homePage/services/Services'
export { default as Destinations } from '@/components/homePage/destinations/Destinations'
export { default as Trips } from '@/components/homePage/trips/Trips'
