import type { Metadata } from 'next'
import './globals.css'
import StoreProvider from '@/app/StoreProvider'
import { Header } from '@/components/homePage'
import { Google_Sans, Montserrat, Open_Sans, Poppins, Volkhov } from 'next/font/google'

export const metadata: Metadata = {
	title: 'Service App',
	description: 'Generated by create next app',
}

const googleSans = Google_Sans({
	subsets: ['latin'],
	weight: ['400', '500'],
	variable: '--font-google-sans',
})

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '600', '700'],
	variable: '--font-poppins',
})

const volkhov = Volkhov({
	subsets: ['latin'],
	weight: ['700'],
	variable: '--font-volkhov',
})

const openSans = Open_Sans({
	subsets: ['latin'],
	weight: ['600'],
	variable: '--font-open-sans',
})

const montserrat = Montserrat({
	subsets: ['latin'],
	weight: ['400'],
	variable: '--font-montserrat',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			className={` ${googleSans.variable} ${poppins.variable} ${volkhov.variable} ${openSans.variable} ${montserrat.variable}`}
		>
			<body>
				<div className={'content-container'}>
					<StoreProvider>
						<Header />
						{children}
					</StoreProvider>
				</div>
			</body>
		</html>
	)
}
