import type { Metadata } from 'next'
import './globals.css'
import StoreProvider from '@/app/StoreProvider'
import { Header, Hero } from '@/components/homePage'

export const metadata: Metadata = {
	title: 'Service App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<StoreProvider>
					<div className={'content-container'}>
						<Header />
						{children}
					</div>
				</StoreProvider>
			</body>
		</html>
	)
}
